name: Scrape and Update File List

on:
  schedule:
    - cron: '0 0 * * *' # Run the workflow every day at 00:00 UTC

jobs:
  scrape_and_update:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci

    - name: Run scraper.js script
      run: node scraper.js

    - name: Run updateFileList.js script
      run: node updateFileList.js

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add data/*
        git commit -m "Update job data and file list"
        git push

    - name: Deploy to GitHub Pages
      run: node deploy.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
