name: Scrape Jobs and Deploy

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Print Node.js version
        run: node --version

      - name: Install dependencies
        run: npm install

      - name: Scrape jobs
        run: node scraper.js

      - name: Update fileList.json
        run: node updateFileList.js
        working-directory: ./

      - name: Deploy to GitHub Pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout --orphan gh-pages
          git add data
          git commit -m "Deploy to GitHub Pages"
          git push https://${GITHUB_TOKEN}@github.com/cmurgu/mapping-jobs.git gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
